In [94]:
import pandas as pd
import numpy as np

In [95]:
split1 = pd.read_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/prophet_split/prophet_split1.csv')
split2 = pd.read_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/prophet_split/prophet_split2.csv')
split3 = pd.read_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/prophet_split/prophet_split3.csv')
split4 = pd.read_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/prophet_split/prophet_split4.csv')

In [96]:
submission_sample = pd.read_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/data/sample_submission.csv')
first_pro = pd.read_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/submission/submission_prophet2_ALL.csv')

In [97]:
split1.drop(['Unnamed: 0','id'], axis = 1, inplace = True)

In [98]:
split2.drop(['Unnamed: 0','id'], axis = 1, inplace = True)
split3.drop(['Unnamed: 0','id'], axis = 1, inplace = True)
split4.drop(['Unnamed: 0','id'], axis = 1, inplace = True)

In [99]:
split_all = split1.copy()

In [100]:
split1 = split1[:7623]

In [101]:
split2 = split2[:7623]

In [102]:
split3 = split3[:7622]

In [103]:
split4 = split4[:7622]

In [104]:
joined_df = pd.concat([split1,split2,split3,split4], ignore_index= True)

In [105]:
joined_df

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,0.715834,0.915793,0.737153,0.679746,0.885750,1.151936,0.678581,0.448104,0.537807,0.266069,...,0.415860,0.845347,0.510377,0.404532,0.613663,0.440994,0.380257,0.562619,0.790143,0.286786
1,0.264101,0.313151,0.088360,0.134565,0.232568,0.329751,0.415052,0.221736,0.234972,0.171694,...,0.447401,0.267362,0.258397,0.249646,0.518572,0.510354,0.592417,0.576734,0.595804,0.752049
2,0.491322,0.397691,0.396348,0.427642,0.639625,0.938232,0.755672,0.751628,0.767075,0.883746,...,0.844222,0.962871,0.647044,0.571320,0.527490,0.557782,0.570953,0.738083,1.011158,0.834226
3,0.935152,0.403906,0.743346,1.628049,1.652262,3.151034,4.271298,1.631538,0.975994,0.726725,...,1.541868,3.331793,4.421388,1.456839,0.630589,0.709179,1.575434,1.676340,3.055393,3.819275
4,1.520631,1.583654,1.547123,1.662655,1.913801,2.095398,2.007565,1.138840,0.973746,0.754846,...,0.649631,0.884216,1.100852,0.667768,0.875198,0.871752,0.919011,1.111182,1.336117,1.380919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,0.068178,0.122574,0.171256,0.074621,0.172911,0.030665,0.234287,0.034646,0.134465,0.207022,...,0.331390,0.168788,0.257655,0.000000,0.000000,0.000754,0.033212,0.284490,0.250225,0.492118
30486,0.000000,0.000000,0.000000,0.000000,0.000000,0.110560,0.129694,0.151738,0.159885,0.310172,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.058757,0.115362
30487,0.642562,0.190419,0.580048,0.373021,0.522492,0.517122,0.980351,1.078983,0.715067,1.131186,...,0.459840,0.329424,0.660416,0.626097,0.148843,0.504785,0.243673,0.306951,0.166136,0.432952
30488,1.339985,1.422067,1.303961,1.296537,1.253221,1.450000,1.620919,1.388948,1.400106,1.245041,...,1.460391,1.514734,1.466517,1.041591,0.964087,0.815624,0.855147,0.859659,1.067487,1.232828
30489,2.414532,3.070942,2.354127,2.285507,2.863463,2.921335,3.452406,3.424529,3.679956,2.626624,...,2.299092,2.197733,2.404225,2.155544,2.445736,1.604331,1.523662,2.058081,2.035793,2.561073

In [106]:
test = joined_df.copy()

In [107]:
submission_sample

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,FOODS_3_823_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60976,FOODS_3_824_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60977,FOODS_3_825_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60978,FOODS_3_826_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60979,FOODS_3_827_WI_3_evaluation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [108]:
eval_part = first_pro[30490:]
eval_part = eval_part.drop('id', axis=1)

In [109]:
joined_df = pd.concat([joined_df,eval_part], ignore_index= True)

In [110]:
joined_df.shape[0]

60980

In [111]:
id_value = submission_sample['id']

joined_df.insert(loc=0, column='id', value=id_value)

In [112]:
joined_df

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0.715834,0.915793,0.737153,0.679746,0.885750,1.151936,0.678581,0.448104,0.537807,...,0.415860,0.845347,0.510377,0.404532,0.613663,0.440994,0.380257,0.562619,0.790143,0.286786
1,HOBBIES_1_002_CA_1_validation,0.264101,0.313151,0.088360,0.134565,0.232568,0.329751,0.415052,0.221736,0.234972,...,0.447401,0.267362,0.258397,0.249646,0.518572,0.510354,0.592417,0.576734,0.595804,0.752049
2,HOBBIES_1_003_CA_1_validation,0.491322,0.397691,0.396348,0.427642,0.639625,0.938232,0.755672,0.751628,0.767075,...,0.844222,0.962871,0.647044,0.571320,0.527490,0.557782,0.570953,0.738083,1.011158,0.834226
3,HOBBIES_1_004_CA_1_validation,0.935152,0.403906,0.743346,1.628049,1.652262,3.151034,4.271298,1.631538,0.975994,...,1.541868,3.331793,4.421388,1.456839,0.630589,0.709179,1.575434,1.676340,3.055393,3.819275
4,HOBBIES_1_005_CA_1_validation,1.520631,1.583654,1.547123,1.662655,1.913801,2.095398,2.007565,1.138840,0.973746,...,0.649631,0.884216,1.100852,0.667768,0.875198,0.871752,0.919011,1.111182,1.336117,1.380919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,FOODS_3_823_WI_3_evaluation,0.225189,0.093887,0.126004,0.087226,0.140300,0.104034,0.186041,0.159492,0.040336,...,0.201617,0.185599,0.285324,0.273542,0.165873,0.219367,0.199201,0.267699,0.243348,0.333543
60976,FOODS_3_824_WI_3_evaluation,0.089006,0.001973,0.003428,0.014074,-0.038105,-0.004242,0.078246,0.052521,-0.042455,...,-0.099108,-0.050072,0.050888,0.046501,-0.024792,-0.004003,0.029166,0.002191,0.063347,0.174559
60977,FOODS_3_825_WI_3_evaluation,0.397447,0.243549,0.209129,0.192611,0.283792,0.568202,0.527096,0.489206,0.328561,...,0.280446,0.540158,0.476173,0.418094,0.240759,0.184479,0.148611,0.223821,0.496414,0.448304
60978,FOODS_3_826_WI_3_evaluation,1.729231,1.789361,1.681637,1.698416,1.677224,1.777119,1.895829,1.763083,1.833970,...,1.807351,1.902747,2.013328,1.868971,1.925014,1.809298,1.814311,1.777822,1.859238,1.956733
60979,FOODS_3_827_WI_3_evaluation,1.933008,2.013490,1.770946,1.653288,1.855659,1.952332,1.838767,1.842551,1.939166,...,1.863146,1.972887,1.868230,1.876537,1.973190,1.742705,1.632648,1.837948,1.932810,1.812764

In [79]:
joined_df.to_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/submission/prophet_tuned_without_eval_computed.csv')

In [113]:
split_all

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,0.715834,0.915793,0.737153,0.679746,0.885750,1.151936,0.678581,0.448104,0.537807,0.266069,...,0.415860,0.845347,0.510377,0.404532,0.613663,0.440994,0.380257,0.562619,0.790143,0.286786
1,0.264101,0.313151,0.088360,0.134565,0.232568,0.329751,0.415052,0.221736,0.234972,0.171694,...,0.447401,0.267362,0.258397,0.249646,0.518572,0.510354,0.592417,0.576734,0.595804,0.752049
2,0.491322,0.397691,0.396348,0.427642,0.639625,0.938232,0.755672,0.751628,0.767075,0.883746,...,0.844222,0.962871,0.647044,0.571320,0.527490,0.557782,0.570953,0.738083,1.011158,0.834226
3,0.935152,0.403906,0.743346,1.628049,1.652262,3.151034,4.271298,1.631538,0.975994,0.726725,...,1.541868,3.331793,4.421388,1.456839,0.630589,0.709179,1.575434,1.676340,3.055393,3.819275
4,1.520631,1.583654,1.547123,1.662655,1.913801,2.095398,2.007565,1.138840,0.973746,0.754846,...,0.649631,0.884216,1.100852,0.667768,0.875198,0.871752,0.919011,1.111182,1.336117,1.380919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60977,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60978,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60979,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [115]:
fake_eval = split_all[30490:]
fake_eval

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
30490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30492,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30493,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30494,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60979,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [116]:
test

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,0.715834,0.915793,0.737153,0.679746,0.885750,1.151936,0.678581,0.448104,0.537807,0.266069,...,0.415860,0.845347,0.510377,0.404532,0.613663,0.440994,0.380257,0.562619,0.790143,0.286786
1,0.264101,0.313151,0.088360,0.134565,0.232568,0.329751,0.415052,0.221736,0.234972,0.171694,...,0.447401,0.267362,0.258397,0.249646,0.518572,0.510354,0.592417,0.576734,0.595804,0.752049
2,0.491322,0.397691,0.396348,0.427642,0.639625,0.938232,0.755672,0.751628,0.767075,0.883746,...,0.844222,0.962871,0.647044,0.571320,0.527490,0.557782,0.570953,0.738083,1.011158,0.834226
3,0.935152,0.403906,0.743346,1.628049,1.652262,3.151034,4.271298,1.631538,0.975994,0.726725,...,1.541868,3.331793,4.421388,1.456839,0.630589,0.709179,1.575434,1.676340,3.055393,3.819275
4,1.520631,1.583654,1.547123,1.662655,1.913801,2.095398,2.007565,1.138840,0.973746,0.754846,...,0.649631,0.884216,1.100852,0.667768,0.875198,0.871752,0.919011,1.111182,1.336117,1.380919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,0.068178,0.122574,0.171256,0.074621,0.172911,0.030665,0.234287,0.034646,0.134465,0.207022,...,0.331390,0.168788,0.257655,0.000000,0.000000,0.000754,0.033212,0.284490,0.250225,0.492118
30486,0.000000,0.000000,0.000000,0.000000,0.000000,0.110560,0.129694,0.151738,0.159885,0.310172,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.058757,0.115362
30487,0.642562,0.190419,0.580048,0.373021,0.522492,0.517122,0.980351,1.078983,0.715067,1.131186,...,0.459840,0.329424,0.660416,0.626097,0.148843,0.504785,0.243673,0.306951,0.166136,0.432952
30488,1.339985,1.422067,1.303961,1.296537,1.253221,1.450000,1.620919,1.388948,1.400106,1.245041,...,1.460391,1.514734,1.466517,1.041591,0.964087,0.815624,0.855147,0.859659,1.067487,1.232828
30489,2.414532,3.070942,2.354127,2.285507,2.863463,2.921335,3.452406,3.424529,3.679956,2.626624,...,2.299092,2.197733,2.404225,2.155544,2.445736,1.604331,1.523662,2.058081,2.035793,2.561073

In [117]:
test = pd.concat([test,fake_eval], ignore_index= True)

In [118]:
test

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,0.715834,0.915793,0.737153,0.679746,0.885750,1.151936,0.678581,0.448104,0.537807,0.266069,...,0.415860,0.845347,0.510377,0.404532,0.613663,0.440994,0.380257,0.562619,0.790143,0.286786
1,0.264101,0.313151,0.088360,0.134565,0.232568,0.329751,0.415052,0.221736,0.234972,0.171694,...,0.447401,0.267362,0.258397,0.249646,0.518572,0.510354,0.592417,0.576734,0.595804,0.752049
2,0.491322,0.397691,0.396348,0.427642,0.639625,0.938232,0.755672,0.751628,0.767075,0.883746,...,0.844222,0.962871,0.647044,0.571320,0.527490,0.557782,0.570953,0.738083,1.011158,0.834226
3,0.935152,0.403906,0.743346,1.628049,1.652262,3.151034,4.271298,1.631538,0.975994,0.726725,...,1.541868,3.331793,4.421388,1.456839,0.630589,0.709179,1.575434,1.676340,3.055393,3.819275
4,1.520631,1.583654,1.547123,1.662655,1.913801,2.095398,2.007565,1.138840,0.973746,0.754846,...,0.649631,0.884216,1.100852,0.667768,0.875198,0.871752,0.919011,1.111182,1.336117,1.380919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60977,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60978,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60979,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [119]:
test.insert(loc=0, column='id', value=id_value)

In [120]:
test

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0.715834,0.915793,0.737153,0.679746,0.885750,1.151936,0.678581,0.448104,0.537807,...,0.415860,0.845347,0.510377,0.404532,0.613663,0.440994,0.380257,0.562619,0.790143,0.286786
1,HOBBIES_1_002_CA_1_validation,0.264101,0.313151,0.088360,0.134565,0.232568,0.329751,0.415052,0.221736,0.234972,...,0.447401,0.267362,0.258397,0.249646,0.518572,0.510354,0.592417,0.576734,0.595804,0.752049
2,HOBBIES_1_003_CA_1_validation,0.491322,0.397691,0.396348,0.427642,0.639625,0.938232,0.755672,0.751628,0.767075,...,0.844222,0.962871,0.647044,0.571320,0.527490,0.557782,0.570953,0.738083,1.011158,0.834226
3,HOBBIES_1_004_CA_1_validation,0.935152,0.403906,0.743346,1.628049,1.652262,3.151034,4.271298,1.631538,0.975994,...,1.541868,3.331793,4.421388,1.456839,0.630589,0.709179,1.575434,1.676340,3.055393,3.819275
4,HOBBIES_1_005_CA_1_validation,1.520631,1.583654,1.547123,1.662655,1.913801,2.095398,2.007565,1.138840,0.973746,...,0.649631,0.884216,1.100852,0.667768,0.875198,0.871752,0.919011,1.111182,1.336117,1.380919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60975,FOODS_3_823_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60976,FOODS_3_824_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60977,FOODS_3_825_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60978,FOODS_3_826_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60979,FOODS_3_827_WI_3_evaluation,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [121]:
test.to_csv('/Users/jerem/cours_esiee_paris/E4/kaggle_walmart/submission/test_metric_computation.csv')